f = figure;
f.Position(1:4) = [0 0 1920 1080];
hold on;
plot(t, zeros(length(t), 1),...
    "Color", "black",...
    "Marker", ".");
plot([t(1, 1)], [0.0],...
    "Color", "magenta",...
    "Marker", "o",...
    "MarkerSize", 8);
plot(real(z), imag(z),...
    "Color", "black",...
    "Marker",".");
for m = 1 : 1 : length(z)
    temp1 = [real(z(m, 1)); real(z(m, 1) + d_z(m, 1))];
    temp2 = [imag(z(m, 1)); imag(z(m, 1) + d_z(m, 1))];
    plot(temp1, temp2,...
        "Color", "red",...
        "Marker",".");
end
plot([real(z(1, 1))], [imag(z(1, 1))],...
    "Color", "magenta",...
    "Marker", "o",...
    "MarkerSize", 8);
axis equal;
saveas(gcf, strcat(path_to_graph, "mesh"), 'fig');
saveas(gcf, strcat(path_to_graph, "mesh"), 'png');